name: maidmatch
description: "Your Perfect Maid is Just a Match Away"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  firebase_core: ^2.24.2
  firebase_auth: ^4.15.3
  cloud_firestore: ^4.13.6
  firebase_storage: ^11.5.6
  provider: ^6.1.1
  google_maps_flutter: ^2.5.0
  geocoding: ^2.1.1
  geolocator: ^10.1.0
  image_picker: ^1.0.5
  intl: ^0.19.0
  shared_preferences: ^2.2.2
  http: ^0.13.5
  latlong2: ^0.9.0
  file_picker: ^5.5.0
  url_launcher: ^6.1.14
  cached_network_image: ^3.3.0
  flutter_svg: ^2.0.7
  google_fonts: ^4.0.4
  map_launcher: ^2.5.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  
  assets:
    - assets/
    - assets/images/
    - assets/icons/
    - assets/wel.jpg
